GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Udin1",
  "email": "udin2@gmail.com",
  "password": "udin12345",
  "confPassword": "udin12345"
}
###
GET http://localhost:3000/login
Content-Type: application/json

{
  "email": "udin2@gmail.com",
  "password": "udin12345"
}